S2_RESULTS_PER_QUERY = 50
ARXIV_RESULTS_PER_QUERY = 15
OPENALEX_RESULTS_PER_QUERY = 30

MAX_RESULTS = 20

GRAPH_EXPANSION_DEPTH = 2
GRAPH_EXPANSION_MAX_PER_HOP = 40
SEED_RELEVANCE_THRESHOLD = 6
MAX_SEEDS_PER_HOP = 20
